src/Entity/ImageFetchTask.php
<?php

namespace App\Entity;

use App\Repository\ImageFetchTaskRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;

#[ORM\Entity(repositoryClass: ImageFetchTaskRepository::class)]
class ImageFetchTask
{
    const STATUS_NEW = 'new';
    const STATUS_PROGRESS = 'progress';
    const STATUS_READY = 'ready';

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "CUSTOM")]
    #[ORM\Column(type: "uuid", unique: true)]
    #[ORM\CustomIdGenerator(class:UuidGenerator::class)]
    private ?string $id = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(length: 32)]
    private ?string $status = null;

    #[ORM\Column(nullable: true)]
    private ?array $data = null;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getData(): ?array
    {
        return $this->data;
    }

    public function setData(?array $data): static
    {
        $this->data = $data;

        return $this;
    }

    public function getTotalSize(): int
    {
        return $this->data['total_size'] ?? 0;
    }

    public function getErrorCount(): int
    {
        return $this->data['error_count'] ?? 0;
    }

    public function getCount(): int
    {
        return count($this->data['images'] ?? []);
    }
}

src/Form/ImageFetchTaskType.php
<?php

namespace App\Form;

use App\Entity\ImageFetchTask;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImageFetchTaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('url')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ImageFetchTask::class,
        ]);
    }
}

src/Controller/ImageFetchTaskController.php
<?php

namespace App\Controller;

use App\Entity\ImageFetchTask;
use App\Form\ImageFetchTaskType;
use App\Message\ImageFetchTaskCreatedMessage;
use App\Repository\ImageFetchTaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/image/fetch/task')]
class ImageFetchTaskController extends AbstractController
{
    #[Route('/', name: 'app_image_fetch_task_index', methods: ['GET'])]
    public function index(ImageFetchTaskRepository $imageFetchTaskRepository): Response
    {
        return $this->render('image_fetch_task/index.html.twig', [
            'image_fetch_tasks' => $imageFetchTaskRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_image_fetch_task_new', methods: ['GET', 'POST'])]
    public function new(
        Request $request,
        EntityManagerInterface $entityManager,
        MessageBusInterface $bus,
    ): Response
    {
        $imageFetchTask = new ImageFetchTask();
        $form = $this->createForm(ImageFetchTaskType::class, $imageFetchTask);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFetchTask->setStatus(ImageFetchTask::STATUS_NEW);
            $entityManager->persist($imageFetchTask);
            $entityManager->flush();

            $bus->dispatch(new ImageFetchTaskCreatedMessage($imageFetchTask->getId()));

            $this->addFlash('info', 'Task added');

            return $this->redirectToRoute('app_image_fetch_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('image_fetch_task/new.html.twig', [
            'image_fetch_task' => $imageFetchTask,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_image_fetch_task_show', methods: ['GET'])]
    public function show(ImageFetchTask $imageFetchTask): Response
    {
        return $this->render('image_fetch_task/show.html.twig', [
            'image_fetch_task' => $imageFetchTask,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_image_fetch_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ImageFetchTask $imageFetchTask, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ImageFetchTaskType::class, $imageFetchTask);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_image_fetch_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('image_fetch_task/edit.html.twig', [
            'image_fetch_task' => $imageFetchTask,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_image_fetch_task_delete', methods: ['POST'])]
    public function delete(Request $request, ImageFetchTask $imageFetchTask, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$imageFetchTask->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($imageFetchTask);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_image_fetch_task_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        {% endblock %}

        {% block javascripts %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
        <style>
            .inline {
                display: inline;
            }
        </style>
    </head>
    <body>
    <div class="container">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ label }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endfor %}
        {% block body %}{% endblock %}
    </div>
    </body>
</html>

templates/image_fetch_task/_delete_form.html.twig
<form method="post" action="{{ path('app_image_fetch_task_delete', {'id': image_fetch_task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ image_fetch_task.id) }}">
    <button class="btn btn-secondary">Delete</button>
</form>

templates/image_fetch_task/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/image_fetch_task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ImageFetchTask{% endblock %}

{% block body %}
    <h1>Edit ImageFetchTask</h1>

    {{ include('image_fetch_task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_image_fetch_task_index') }}">back to list</a>

    {{ include('image_fetch_task/_delete_form.html.twig') }}
{% endblock %}

templates/image_fetch_task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ImageFetchTask index{% endblock %}

{% block body %}
    <h1>ImageFetchTask index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Url</th>
                <th>Status</th>
                <th>Images count</th>
                <th>Total size</th>
                <th>Errors count</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for image_fetch_task in image_fetch_tasks %}
            <tr>
                <td>{{ image_fetch_task.id }}</td>
                <td>{{ image_fetch_task.url }}</td>
                <td>{{ image_fetch_task.status }}</td>
                <td>{{ image_fetch_task.count }}</td>
                <td>{{ image_fetch_task.totalSize |number_format }}</td>
                <td>{{ image_fetch_task.errorCount }}</td>
                <td>
                    <a href="{{ path('app_image_fetch_task_show', {'id': image_fetch_task.id}) }}">show</a>
                    <div class="inline">{{ include('image_fetch_task/_delete_form.html.twig') }}</div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_image_fetch_task_new') }}">Create new</a>
{% endblock %}

templates/image_fetch_task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ImageFetchTask{% endblock %}

{% block body %}
    <h1>Create new ImageFetchTask</h1>

    {{ include('image_fetch_task/_form.html.twig') }}

    <a href="{{ path('app_image_fetch_task_index') }}">back to list</a>
{% endblock %}

templates/image_fetch_task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ImageFetchTask{% endblock %}

{% block body %}
    <h1>ImageFetchTask</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Url</th>
                <td>{{ image_fetch_task.url }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ image_fetch_task.status }}</td>
            </tr>
            <tr>
                <th>Image count</th>
                <td>{{ image_fetch_task.count }}</td>
            </tr>
            <tr>
                <th>Total size</th>
                <td>{{ image_fetch_task.totalSize |number_format }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_image_fetch_task_index') }}">back to list</a>

    {{ include('image_fetch_task/_delete_form.html.twig') }}

    <div class="row">
    {% for path in image_fetch_task.data.images %}
        {% if loop.index0 % 4 == 3 %}
    </div>
    <div class="row">
        {% endif %}
        <div class="col"><img class="img-fluid" src="{{ image_fetch_task.url }}{{ path.path }}" alt=""></div>
    {% endfor %}
    </div>
{% endblock %}